server:
  port: 8082
spring:
  application:
    name: "reporting-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  region: "${AWS_REGION:us-east-2}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
entrypoint:
  sqs:
    region: "${AWS_REGION:us-east-2}"
    queueUrl: "${LISTENER_STATUS_APPROVED_QUEUE:https://sqs.us-east-2.amazonaws.com/343629588964/application-status-approved-queue}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 1
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1